from django.conf.urls import patterns,url

from vetbiz import views
from vetbiz import api

urlpatterns=patterns('',
        url(r'api/getbiz/$',api.getbiz),
        url(r'api/updatebiz/$',api.updatebiz),
        url(r'api/searchbiz/$',api.searchbiz),
        url(r'api/signin/$',api.signin),
        url(r'api/unique/$',api.unique),
        url(r'api/signup/$',api.signup),
        url(r'api/dologout/$',api.dologout),
        url(r'api/checkin/$',api.checkin),
        url(r'api/donate/$',api.donate),
        url(r'api/offers/$',api.offers),
        url(r'api/jobs/$',api.jobs),
        url(r'api/charities/$',api.charities),
        url(r'api/places/$',api.places),
        url(r'search/$',views.search),
        url(r'search$',views.search),
        url(r'checkins/$',views.checkins),
        url(r'checkins$',views.checkins),
        url(r'donations/$',views.donations),
        url(r'donations$',views.donations),
        url(r'offers/$',views.offers),
        url(r'createoffer/(?P<place_id>\d+)',views.createoffer),
        url(r'saveofferedit/(?P<offer_id>\d+)',views.saveofferedit),
        url(r'offeredit/(?P<offer_id>\d+)',views.offeredit),
        url(r'deleteoffer/(?P<offer_id>\d+)',views.deleteoffer),
        url(r'saveoffer/(?P<place_id>\d+)',views.saveoffer),
        url(r'offers$',views.offers),
        url(r'offer/(?P<offer_id>\d+)',views.offer),
        url(r'createjob/(?P<place_id>\d+)',views.createjob),
        url(r'createoffer/(?P<place_id>\d+)',views.createoffer),
        url(r'savejobedit/(?P<job_id>\d+)',views.savejobedit),
        url(r'jobedit/(?P<job_id>\d+)',views.jobedit),
        url(r'deletejob/(?P<job_id>\d+)',views.deletejob),
        url(r'savejob/(?P<place_id>\d+)',views.savejob),
        url(r'job/(?P<job_id>\d+)',views.job),
        url(r'saveplace/(?P<place_id>\d+)',views.saveplace),
        url(r'place/(?P<place_id>\d+)',views.place),
        url(r'charity/(?P<charity_id>\d+)',views.charity),
        url(r'placeadmin/(?P<place_id>\d+)',views.placeadmin),
        url(r'placeedit/(?P<place_id>\d+)',views.placeedit),
        url(r'jobs/$',views.jobs),
        url(r'jobs$',views.jobs),
        url(r'places$',views.places),
        url(r'places/$',views.places),
        url(r'charities$',views.charities),
        url(r'charities/$',views.charities),
        url(r'profile$',views.profile),
        url(r'profile/$',views.profile),
        url(r'signin/$',views.signin),
        url(r'signin$',views.signin),
        url(r'signup/$',views.signup),
        url(r'signup$',views.signup),
        url(r'/$',views.search),
        url(r'$',views.search))

